version: '3.8'

services:
  transcription-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - models_volume:/app/models
      - data_volume:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  models_volume:
    driver: local
  data_volume:
    driver: local